version: '3.7'

# after docker-compose up
# docker exec -it <container_name> bash
# psql -U postgres
# create database <db_name>;

services:
  database:
    image: postgres:14 # PostgreSQL image
    ports:
      - "5432:5432" # Port 5432 to port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always # Restart the container if it exits
    networks:
      - default # Connect to the default network